# Generated by Django 4.2 on 2023-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_openadmissionmodel_post_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openadmissionmodel',
            name='post_ad',
            field=models.ImageField(default=False, upload_to='myimage'),
        ),
    ]
