# Generated by Django 4.2 on 2023-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_openadmissionmodel_post_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openadmissionmodel',
            name='post_ad',
            field=models.ImageField(blank=True, upload_to='myimage'),
        ),
    ]
