# Generated by Django 4.2 on 2023-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_openadmissionmodel_post_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openadmissionmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
