# Generated by Django 4.2 on 2023-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Dera Ghazi Khan', 'Dera Ghazi Khan\t'), ('Faisalabad', '\t\tFaisalabad'), ('Gujranwala', '\t\tGujranwala'), ('Lahore', '\t\tLahore'), ('Mianwali', 'Mianwali'), ('Multan\t', 'Multan'), ('Rawalpindi\t', '\tRawalpindi'), ('Sahiwal\t', '\tSahiwal'), ('\tSargodha\t', 'Sargodha'), ('Gujrat\t', '\tGujrat')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('job_city', models.CharField(max_length=70)),
                ('profile_image', models.ImageField(blank=True, upload_to='myimage')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
